
CREATE TABLE CAMPEONATO (
                CODCAMPEONATO int NOT NULL AUTO_INCREMENT,
                NOME_CAMPEONATO VARCHAR(15) NOT NULL,
                USUARIO VARCHAR(18) NOT NULL,
                SENHA VARCHAR(10) NOT NULL,
                PRIMARY KEY (CODCAMPEONATO)
);


CREATE TABLE SEMIS_1 (
                TIME1 VARCHAR(25) NOT NULL,
                TIME2 VARCHAR(25) NOT NULL,
                TIME3 VARCHAR(25) NOT NULL,
                TIME4 VARCHAR(25) NOT NULL,
                CODCAMPEONATO INT NOT NULL
);


CREATE TABLE CAMPEAO_1 (
                TIME VARCHAR(25) NOT NULL,
                CODCAMPEONATO INT NOT NULL
);


CREATE TABLE JOGOS_BR_1 (
                JOGO1 VARCHAR(2) NOT NULL,
                JOGO2 VARCHAR(2) NOT NULL,
                JOGO3 VARCHAR(2) NOT NULL,
                OITAVAS VARCHAR(2) NOT NULL,
                QUARTAS VARCHAR(2) NOT NULL,
                SEMIS VARCHAR(2) NOT NULL,
                FINAL VARCHAR(2) NOT NULL,
                CODCAMPEONATO INT NOT NULL
);


CREATE TABLE QUARTAS_1 (
                TIME1 VARCHAR(25) NOT NULL,
                TIME2 VARCHAR(25) NOT NULL,
                TIME3 VARCHAR(25) NOT NULL,
                TIME4 VARCHAR(25) NOT NULL,
                TIME5 VARCHAR(25) NOT NULL,
                TIME6 VARCHAR(25) NOT NULL,
                TIME7 VARCHAR(25) NOT NULL,
                TIME8 VARCHAR(25) NOT NULL,
                CODCAMPEONATO INT NOT NULL
);


CREATE TABLE OITAVAS_1 (
                TIME1 VARCHAR(25) NOT NULL,
                TIME2 VARCHAR(25) NOT NULL,
                TIME3 VARCHAR(25) NOT NULL,
                TIME4 VARCHAR(25) NOT NULL,
                TIME5 VARCHAR(25) NOT NULL,
                TIME6 VARCHAR(25) NOT NULL,
                TIME7 VARCHAR(25) NOT NULL,
                TIME8 VARCHAR(25) NOT NULL,
                TIME9 VARCHAR(25) NOT NULL,
                TIME10 VARCHAR(25) NOT NULL,
                TIME11 VARCHAR(25) NOT NULL,
                TIME12 VARCHAR(25) NOT NULL,
                TIME13 VARCHAR(25) NOT NULL,
                TIME14 VARCHAR(25) NOT NULL,
                TIME15 VARCHAR(25) NOT NULL,
                TIME16 VARCHAR(25) NOT NULL,
                CODCAMPEONATO INT NOT NULL
);


CREATE TABLE FINAIS_1 (
                TIME1 VARCHAR(25) NOT NULL,
                TIME2 VARCHAR(25) NOT NULL,
                CODCAMPEONATO INT NOT NULL
);


CREATE TABLE GA_1 (
                CODCAMPEONATO INT NOT NULL,
                POS4 VARCHAR(25),
                POS3 VARCHAR(25),
                POS2 VARCHAR(25),
                POS1 VARCHAR(25)
);


CREATE TABLE GC_1 (
                CODCAMPEONATO INT NOT NULL,
                POS4 VARCHAR(25),
                POS3 VARCHAR(25),
                POS2 VARCHAR(25),
                POS1 VARCHAR(25)
);


CREATE TABLE GF_1 (
                CODCAMPEONATO INT NOT NULL,
                POS4 VARCHAR(25),
                POS3 VARCHAR(25),
                POS2 VARCHAR(25),
                POS1 VARCHAR(25)
);


CREATE TABLE GH_1 (
                CODCAMPEONATO INT NOT NULL,
                POS4 VARCHAR(25),
                POS3 VARCHAR(25),
                POS2 VARCHAR(25),
                POS1 VARCHAR(25)
);


CREATE TABLE GB_1 (
                CODCAMPEONATO INT NOT NULL,
                POS4 VARCHAR(25),
                POS3 VARCHAR(25),
                POS2 VARCHAR(25),
                POS1 VARCHAR(25)
);


CREATE TABLE GE_1 (
                CODCAMPEONATO INT NOT NULL,
                POS4 VARCHAR(25),
                POS3 VARCHAR(25),
                POS2 VARCHAR(25),
                POS1 VARCHAR(25)
);


CREATE TABLE GD_1 (
                POS4 VARCHAR(25),
                POS3 VARCHAR(25),
                POS2 VARCHAR(25),
                POS1 VARCHAR(25),
                CODCAMPEONATO INT NOT NULL
);


CREATE TABLE GG_1 (
                CODCAMPEONATO INT NOT NULL,
                POS4 VARCHAR(25),
                POS3 VARCHAR(25),
                POS2 VARCHAR(25),
                POS1 VARCHAR(25)
);


CREATE TABLE CADASTRO (
                CODCADASTRO int NOT NULL AUTO_INCREMENT,
                USUARIO VARCHAR(15) NOT NULL,
                NOME VARCHAR(30) NOT NULL,
                SENHA VARCHAR(18) NOT NULL,
                EMAIL VARCHAR(35) NOT NULL,
                PONTUACAO INT,
                PRIMARY KEY (CODCADASTRO)
);


CREATE TABLE QUARTAS (
                TIME1 VARCHAR(25) NOT NULL,
                TIME2 VARCHAR(25) NOT NULL,
                TIME3 VARCHAR(25) NOT NULL,
                TIME4 VARCHAR(25) NOT NULL,
                TIME5 VARCHAR(25) NOT NULL,
                TIME6 VARCHAR(25) NOT NULL,
                TIME7 VARCHAR(25) NOT NULL,
                TIME8 VARCHAR(25) NOT NULL,
                CODCADASTRO INT NOT NULL
);


CREATE TABLE SEMIS (
                CODCADASTRO INT NOT NULL,
                POS4 VARCHAR(25),
                POS3 VARCHAR(25),
                POS2 VARCHAR(25),
                POS1 VARCHAR(25)
);


CREATE TABLE JOGOS_BR (
                JOGO1 VARCHAR(2) NOT NULL,
                JOGO2 VARCHAR(2) NOT NULL,
                JOGO3 VARCHAR(2) NOT NULL,
                OITAVAS VARCHAR(2) NOT NULL,
                QUARTAS VARCHAR(2) NOT NULL,
                SEMIS VARCHAR(2) NOT NULL,
                FINAL VARCHAR(2) NOT NULL,
                CODCADASTRO INT NOT NULL
);


CREATE TABLE GD (
                CODCADASTRO INT NOT NULL,
                POS4 VARCHAR(25),
                POS3 VARCHAR(25),
                POS2 VARCHAR(25),
                POS1 VARCHAR(25)
);


CREATE TABLE GH (
                CODCADASTRO INT NOT NULL,
                POS4 VARCHAR(25),
                POS3 VARCHAR(25),
                POS2 VARCHAR(25),
                POS1 VARCHAR(25)
);


CREATE TABLE CAMPEAO (
                TIME VARCHAR(25) NOT NULL,
                CODCADASTRO INT NOT NULL
);


CREATE TABLE FINAIS (
                TIME1 VARCHAR(25) NOT NULL,
                TIME2 VARCHAR(25) NOT NULL,
                CODCADASTRO INT NOT NULL
);


CREATE TABLE GC (
                POS4 VARCHAR(25),
                POS3 VARCHAR(25),
                POS2 VARCHAR(25),
                POS1 VARCHAR(25),
                CODCADASTRO INT NOT NULL
);


CREATE TABLE GG (
                POS4 VARCHAR(25),
                POS3 VARCHAR(25),
                POS2 VARCHAR(25),
                POS1 VARCHAR(25),
                CODCADASTRO INT NOT NULL
);


CREATE TABLE GF (
                CODCADASTRO INT NOT NULL,
                POS4 VARCHAR(25),
                POS3 VARCHAR(25),
                POS2 VARCHAR(25),
                POS1 VARCHAR(25)
);


CREATE TABLE GB (
                POS4 VARCHAR(25),
                POS3 VARCHAR(25),
                POS2 VARCHAR(25),
                POS1 VARCHAR(25),
                CODCADASTRO INT NOT NULL
);


CREATE TABLE OITAVAS (
                TIME1 VARCHAR(25) NOT NULL,
                TIME2 VARCHAR(25) NOT NULL,
                TIME3 VARCHAR(25) NOT NULL,
                TIME4 VARCHAR(25) NOT NULL,
                TIME5 VARCHAR(25) NOT NULL,
                TIME6 VARCHAR(25) NOT NULL,
                TIME7 VARCHAR(25) NOT NULL,
                TIME8 VARCHAR(25) NOT NULL,
                TIME9 VARCHAR(25) NOT NULL,
                TIME10 VARCHAR(25) NOT NULL,
                TIME11 VARCHAR(25) NOT NULL,
                TIME12 VARCHAR(25) NOT NULL,
                TIME13 VARCHAR(25) NOT NULL,
                TIME14 VARCHAR(25) NOT NULL,
                TIME15 VARCHAR(25) NOT NULL,
                TIME16 VARCHAR(25) NOT NULL,
                CODCADASTRO INT NOT NULL
);


CREATE TABLE GE (
                POS4 VARCHAR(25),
                POS3 VARCHAR(25),
                POS2 VARCHAR(25),
                POS1 VARCHAR(25),
                CODCADASTRO INT NOT NULL
);


CREATE TABLE GA (
                POS1 VARCHAR(25),
                POS2 VARCHAR(25),
                POS3 VARCHAR(25),
                POS4 VARCHAR(25),
                CODCADASTRO INT NOT NULL
);


ALTER TABLE GG_1 ADD CONSTRAINT campeonato_gg_1_fk
FOREIGN KEY (CODCAMPEONATO)
REFERENCES CAMPEONATO (CODCAMPEONATO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE GD_1 ADD CONSTRAINT campeonato_gd_1_fk
FOREIGN KEY (CODCAMPEONATO)
REFERENCES CAMPEONATO (CODCAMPEONATO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE GE_1 ADD CONSTRAINT campeonato_ge_1_fk
FOREIGN KEY (CODCAMPEONATO)
REFERENCES CAMPEONATO (CODCAMPEONATO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE GB_1 ADD CONSTRAINT campeonato_gb_1_fk
FOREIGN KEY (CODCAMPEONATO)
REFERENCES CAMPEONATO (CODCAMPEONATO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE GH_1 ADD CONSTRAINT campeonato_gh_1_fk
FOREIGN KEY (CODCAMPEONATO)
REFERENCES CAMPEONATO (CODCAMPEONATO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE GF_1 ADD CONSTRAINT campeonato_gf_1_fk
FOREIGN KEY (CODCAMPEONATO)
REFERENCES CAMPEONATO (CODCAMPEONATO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE GC_1 ADD CONSTRAINT campeonato_gc_1_fk
FOREIGN KEY (CODCAMPEONATO)
REFERENCES CAMPEONATO (CODCAMPEONATO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE GA_1 ADD CONSTRAINT campeonato_ga_1_fk
FOREIGN KEY (CODCAMPEONATO)
REFERENCES CAMPEONATO (CODCAMPEONATO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE FINAIS_1 ADD CONSTRAINT campeonato_finais_1_fk
FOREIGN KEY (CODCAMPEONATO)
REFERENCES CAMPEONATO (CODCAMPEONATO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE OITAVAS_1 ADD CONSTRAINT campeonato_oitavas_1_fk
FOREIGN KEY (CODCAMPEONATO)
REFERENCES CAMPEONATO (CODCAMPEONATO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE QUARTAS_1 ADD CONSTRAINT campeonato_quartas_1_fk
FOREIGN KEY (CODCAMPEONATO)
REFERENCES CAMPEONATO (CODCAMPEONATO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE JOGOS_BR_1 ADD CONSTRAINT campeonato_jogos_br_1_fk
FOREIGN KEY (CODCAMPEONATO)
REFERENCES CAMPEONATO (CODCAMPEONATO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE CAMPEAO_1 ADD CONSTRAINT campeonato_campeao_1_fk
FOREIGN KEY (CODCAMPEONATO)
REFERENCES CAMPEONATO (CODCAMPEONATO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE SEMIS_1 ADD CONSTRAINT campeonato_semis_1_fk
FOREIGN KEY (CODCAMPEONATO)
REFERENCES CAMPEONATO (CODCAMPEONATO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE GA ADD CONSTRAINT cadastro_ga_fk
FOREIGN KEY (CODCADASTRO)
REFERENCES CADASTRO (CODCADASTRO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE GE ADD CONSTRAINT cadastro_ge_fk
FOREIGN KEY (CODCADASTRO)
REFERENCES CADASTRO (CODCADASTRO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE OITAVAS ADD CONSTRAINT cadastro_oitavas_fk
FOREIGN KEY (CODCADASTRO)
REFERENCES CADASTRO (CODCADASTRO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE GB ADD CONSTRAINT cadastro_gb_fk
FOREIGN KEY (CODCADASTRO)
REFERENCES CADASTRO (CODCADASTRO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE GF ADD CONSTRAINT cadastro_gf_fk
FOREIGN KEY (CODCADASTRO)
REFERENCES CADASTRO (CODCADASTRO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE GG ADD CONSTRAINT cadastro_gg_fk
FOREIGN KEY (CODCADASTRO)
REFERENCES CADASTRO (CODCADASTRO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE GC ADD CONSTRAINT cadastro_gc_fk
FOREIGN KEY (CODCADASTRO)
REFERENCES CADASTRO (CODCADASTRO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE FINAIS ADD CONSTRAINT cadastro_finais_fk
FOREIGN KEY (CODCADASTRO)
REFERENCES CADASTRO (CODCADASTRO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE CAMPEAO ADD CONSTRAINT cadastro_campeao_fk
FOREIGN KEY (CODCADASTRO)
REFERENCES CADASTRO (CODCADASTRO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE GH ADD CONSTRAINT cadastro_gh_fk
FOREIGN KEY (CODCADASTRO)
REFERENCES CADASTRO (CODCADASTRO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE GD ADD CONSTRAINT cadastro_gd_fk
FOREIGN KEY (CODCADASTRO)
REFERENCES CADASTRO (CODCADASTRO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE JOGOS_BR ADD CONSTRAINT cadastro_jogos_br_fk
FOREIGN KEY (CODCADASTRO)
REFERENCES CADASTRO (CODCADASTRO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE SEMIS ADD CONSTRAINT cadastro_semis_fk
FOREIGN KEY (CODCADASTRO)
REFERENCES CADASTRO (CODCADASTRO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE QUARTAS ADD CONSTRAINT cadastro_quartas_fk
FOREIGN KEY (CODCADASTRO)
REFERENCES CADASTRO (CODCADASTRO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;